import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { DEFAULT_CONFIG } from "../src/config.js";
import {
	branchToTicketId,
	makeBody,
	makeTitle,
	type PrEnv,
	runPr,
} from "../src/pr.js";
import { writeTicket } from "../src/ticket.js";
import type { Ticket } from "../src/types.js";
import {
	initGitRepo,
	makeCommit,
	makeTempDir,
	makeTicket,
	makeTodoDir,
	removeTempDir,
} from "./helpers.js";

function writeConfig(dir: string): void {
	writeFileSync(
		join(dir, ".todo", "config.json"),
		JSON.stringify(DEFAULT_CONFIG, null, 2),
		"utf8",
	);
}

describe("branchToTicketId", () => {
	it("extracts id from todo/<id>", () => {
		expect(branchToTicketId("todo/abc12345")).toBe("abc12345");
	});
	it("returns null for non-todo branches", () => {
		expect(branchToTicketId("main")).toBe(null);
		expect(branchToTicketId("feature/foo")).toBe(null);
	});
});

describe("makeTitle", () => {
	it("returns short summaries unchanged", () => {
		expect(makeTitle("Fix the parser")).toBe("Fix the parser");
	});
	it("truncates long summaries with an ellipsis at 70 chars", () => {
		const long = "x".repeat(100);
		const t = makeTitle(long);
		expect(t.length).toBe(70);
		expect(t.endsWith("…")).toBe(true);
	});
	it("collapses whitespace and trims", () => {
		expect(makeTitle("  multi\n  line\t summary  ")).toBe(
			"multi line summary",
		);
	});
});

describe("makeBody", () => {
	let dir: string;

	beforeEach(() => {
		dir = makeTempDir();
		initGitRepo(dir);
		makeTodoDir(dir);
		writeConfig(dir);
	});

	afterEach(() => {
		removeTempDir(dir);
	});

	it("includes the description for single tickets", () => {
		const t = makeTicket({
			id: "abc12345",
			summary: "Fix parser",
			description: "The parser crashes on empty input.",
			resolution: {
				commit: "1234567abcdef",
				resolved_at: "2026-01-01",
				resolved_by: "test",
				note: "Restored null guard",
			},
		});
		const body = makeBody(t, dir);
		expect(body).toContain("The parser crashes on empty input.");
		expect(body).toContain("## Resolution");
		expect(body).toContain("Restored null guard");
		expect(body).toContain("`1234567`");
		expect(body).toContain("Generated by `todo pr`");
	});

	it("renders a Children section for parents with terminal children", () => {
		const c1 = makeTicket({
			id: "child001",
			summary: "Add A",
			state: "done",
			resolution: {
				commit: "aaaaaaa1111111111",
				resolved_at: "2026-01-01",
				resolved_by: "t",
				note: "Added A endpoint",
			},
		});
		const c2 = makeTicket({
			id: "child002",
			summary: "Add B",
			state: "done",
			resolution: {
				commit: "bbbbbbb1111111111",
				resolved_at: "2026-01-02",
				resolved_by: "t",
				note: "Added B middleware",
			},
		});
		writeTicket(dir, c1);
		writeTicket(dir, c2);

		const parent = makeTicket({
			id: "parent01",
			summary: "Auth flow",
			description: "Implement OAuth login.",
			relationships: { children: ["child001", "child002"] },
			resolution: {
				commit: "ccccccc",
				resolved_at: "2026-01-03",
				resolved_by: "t",
				note: "Auth feature shipped.",
			},
		});
		const body = makeBody(parent, dir);
		expect(body).toContain("## Children");
		expect(body).toContain("**child001**");
		expect(body).toContain("Added A endpoint");
		expect(body).toContain("**child002**");
		expect(body).toContain("Added B middleware");
		expect(body).toContain("Auth feature shipped.");
	});

	it("flags non-terminal children with bold state", () => {
		const c1 = makeTicket({
			id: "child001",
			summary: "wip",
			state: "active",
		});
		writeTicket(dir, c1);
		const parent = makeTicket({
			id: "parent01",
			summary: "x",
			relationships: { children: ["child001"] },
		});
		const body = makeBody(parent, dir);
		expect(body).toContain("**active**");
	});

	it("gracefully handles a missing child file", () => {
		const parent = makeTicket({
			id: "parent01",
			summary: "x",
			relationships: { children: ["missing-id"] },
		});
		const body = makeBody(parent, dir);
		expect(body).toContain("missing-id");
		expect(body).toContain("ticket file missing");
	});
});

describe("runPr (mock PrEnv)", () => {
	let dir: string;

	beforeEach(() => {
		dir = makeTempDir();
		initGitRepo(dir);
		makeTodoDir(dir);
		writeConfig(dir);
		makeCommit(dir, "seed.txt", "seed");
	});

	afterEach(() => {
		removeTempDir(dir);
	});

	function makeMockEnv(overrides: Partial<PrEnv> = {}): {
		env: PrEnv;
		calls: Array<{ tool: "gh" | "git"; args: string[]; input?: string }>;
	} {
		const calls: Array<{
			tool: "gh" | "git";
			args: string[];
			input?: string;
		}> = [];
		const env: PrEnv = {
			hasGh: () => true,
			git: (args) => {
				calls.push({ tool: "git", args });
				return "";
			},
			gh: (args, input) => {
				calls.push({ tool: "gh", args, input });
				if (args[0] === "pr" && args[1] === "view") {
					throw new Error("no existing PR");
				}
				return "https://github.com/example/repo/pull/42";
			},
			...overrides,
		};
		return { env, calls };
	}

	it("errors clearly when gh is missing", () => {
		const t = makeTicket({ id: "abc12345", summary: "Fix" });
		const env: PrEnv = {
			hasGh: () => false,
			git: () => "",
			gh: () => "",
		};
		const res = runPr(dir, "todo/abc12345", t, {}, env);
		expect(res.kind).toBe("error");
		if (res.kind === "error") expect(res.message).toContain("gh");
	});

	it("creates a PR when none exists, returns URL", () => {
		const t = makeTicket({ id: "abc12345", summary: "Fix the parser" });
		const { env, calls } = makeMockEnv();
		const res = runPr(dir, "todo/abc12345", t, {}, env);
		expect(res.kind).toBe("created");
		if (res.kind === "created") {
			expect(res.url).toBe("https://github.com/example/repo/pull/42");
		}
		// Pushed first.
		const push = calls.find(
			(c) => c.tool === "git" && c.args[0] === "push",
		);
		expect(push?.args).toEqual(["push", "-u", "origin", "todo/abc12345"]);
		// Then gh pr view (returns null since we threw), then gh pr create.
		const create = calls.find(
			(c) => c.tool === "gh" && c.args[1] === "create",
		);
		expect(create?.args).toContain("--title");
		expect(create?.args).toContain("Fix the parser");
		// Body footer always references the ticket id.
		expect(create?.input).toContain("abc12345");
	});

	it("updates an existing PR via gh pr edit", () => {
		const t = makeTicket({ id: "abc12345", summary: "Fix" });
		const calls: Array<{
			tool: "gh" | "git";
			args: string[];
			input?: string;
		}> = [];
		const env: PrEnv = {
			hasGh: () => true,
			git: (args) => {
				calls.push({ tool: "git", args });
				return "";
			},
			gh: (args, input) => {
				calls.push({ tool: "gh", args, input });
				if (args[1] === "view") return "https://github.com/x/y/pull/7";
				return "";
			},
		};
		const res = runPr(dir, "todo/abc12345", t, {}, env);
		expect(res.kind).toBe("updated");
		if (res.kind === "updated") {
			expect(res.url).toBe("https://github.com/x/y/pull/7");
		}
		const edit = calls.find(
			(c) => c.tool === "gh" && c.args[1] === "edit",
		);
		expect(edit).toBeTruthy();
	});

	it("propagates --base and --draft to gh pr create", () => {
		const t = makeTicket({ id: "abc12345", summary: "Fix" });
		const { env, calls } = makeMockEnv();
		runPr(
			dir,
			"todo/abc12345",
			t,
			{ base: "dev", draft: true },
			env,
		);
		const create = calls.find(
			(c) => c.tool === "gh" && c.args[1] === "create",
		);
		expect(create?.args).toContain("--base");
		expect(create?.args).toContain("dev");
		expect(create?.args).toContain("--draft");
	});

	it("returns an error when git push fails", () => {
		const t = makeTicket({ id: "abc12345", summary: "Fix" });
		const env: PrEnv = {
			hasGh: () => true,
			git: (args) => {
				if (args[0] === "push") throw new Error("permission denied");
				return "";
			},
			gh: () => "",
		};
		const res = runPr(dir, "todo/abc12345", t, {}, env);
		expect(res.kind).toBe("error");
		if (res.kind === "error") {
			expect(res.message).toContain("push");
			expect(res.message).toContain("permission denied");
		}
	});
});

// ---------------------------------------------------------------------------
// End-to-end: CLI refuses to run off a todo/<id> branch.
// ---------------------------------------------------------------------------

function todoCli(
	dir: string,
	args: string[],
): Promise<{ status: number; stdout: string; stderr: string }> {
	const cliPath = join(__dirname, "..", "dist", "cli.js");
	return new Promise((resolve) => {
		const child = spawn("node", [cliPath, ...args], {
			cwd: dir,
			env: { ...process.env },
		});
		let stdout = "";
		let stderr = "";
		child.stdout.on("data", (d) => {
			stdout += d.toString();
		});
		child.stderr.on("data", (d) => {
			stderr += d.toString();
		});
		child.on("close", (code) => {
			resolve({ status: code ?? 1, stdout, stderr });
		});
	});
}

describe("CLI pr (end-to-end)", () => {
	let dir: string;

	beforeEach(() => {
		dir = makeTempDir();
		initGitRepo(dir);
		makeTodoDir(dir);
		writeConfig(dir);
		makeCommit(dir, "seed.txt", "seed");
	});

	afterEach(() => {
		removeTempDir(dir);
	});

	it("refuses to run from main", async () => {
		const res = await todoCli(dir, ["pr"]);
		expect(res.status).toBe(1);
		expect(res.stderr).toContain("todo/<id>");
	});

	it("refuses when branch references a missing ticket", async () => {
		const { execFileSync } = await import("node:child_process");
		execFileSync("git", ["checkout", "-b", "todo/nonexistent"], { cwd: dir });
		const res = await todoCli(dir, ["pr"]);
		expect(res.status).toBe(1);
		expect(res.stderr).toContain("nonexistent");
	});
});
