// Pull-request creation helpers used by `todo pr`.
//
// The CLI command is a thin wrapper around the `gh` binary plus `git push`,
// with title and body auto-generated from the ticket(s) on the current
// todo/<id> branch. Keeping the formatting and decision logic in this
// module so it can be unit-tested without touching the network.

import { execFileSync } from "node:child_process";
import { readTicket, TERMINAL_STATES } from "./ticket.js";
import type { Ticket } from "./types.js";

const MAX_TITLE_CHARS = 70;

/** Extract the ticket id from a `todo/<id>` branch name. */
export function branchToTicketId(branch: string): string | null {
	const m = branch.match(/^todo\/(.+)$/);
	return m ? (m[1] ?? null) : null;
}

/**
 * Truncate a one-line title to MAX_TITLE_CHARS, ending with an ellipsis
 * when truncated. Single-line input only — strips newlines.
 */
export function makeTitle(summary: string): string {
	const oneLine = summary.replace(/\s+/g, " ").trim();
	if (oneLine.length <= MAX_TITLE_CHARS) return oneLine;
	return `${oneLine.slice(0, MAX_TITLE_CHARS - 1)}…`;
}

function shortSha(sha: string | undefined): string {
	if (!sha) return "";
	return sha.length > 7 ? sha.slice(0, 7) : sha;
}

/**
 * Render the PR body for a given root ticket. For parents, includes a
 * "Children" section with each terminal child's resolution. For single
 * tickets, includes the description and resolution.
 */
export function makeBody(ticket: Ticket, repoRoot: string): string {
	const lines: string[] = [];

	if (ticket.description) {
		lines.push(ticket.description.trim());
		lines.push("");
	}

	const children = ticket.relationships?.children ?? [];
	if (children.length > 0) {
		lines.push("## Children");
		lines.push("");
		for (const childId of children) {
			let child: Ticket;
			try {
				child = readTicket(repoRoot, childId);
			} catch {
				lines.push(`- ${childId} — _ticket file missing_`);
				continue;
			}
			const status = TERMINAL_STATES.includes(child.state)
				? child.state
				: `**${child.state}**`;
			const note = child.resolution?.note ?? "_no note_";
			const sha = shortSha(child.resolution?.commit);
			lines.push(
				`- **${child.id}** (${status}) — ${child.summary}` +
					(sha ? ` _(${sha})_` : "") +
					`\n  ${note}`,
			);
		}
		lines.push("");
	}

	if (ticket.resolution?.note) {
		lines.push("## Resolution");
		lines.push("");
		lines.push(ticket.resolution.note);
		if (ticket.resolution.commit) {
			lines.push("");
			lines.push(`Commit: \`${shortSha(ticket.resolution.commit)}\``);
		}
		lines.push("");
	}

	lines.push("---");
	lines.push(`<sub>Generated by \`todo pr\` from ticket ${ticket.id}.</sub>`);
	return lines.join("\n").trim() + "\n";
}

// ---------------------------------------------------------------------------
// External-process probes (kept thin so tests can swap them)
// ---------------------------------------------------------------------------

export interface PrEnv {
	gh: (args: string[], input?: string) => string;
	git: (args: string[]) => string;
	hasGh: () => boolean;
}

export function defaultPrEnv(cwd: string): PrEnv {
	return {
		gh: (args, input) => {
			return execFileSync("gh", args, {
				cwd,
				encoding: "utf8",
				input,
				stdio: input ? ["pipe", "pipe", "pipe"] : ["ignore", "pipe", "pipe"],
			}).trim();
		},
		git: (args) => execFileSync("git", args, { cwd, encoding: "utf8" }).trim(),
		hasGh: () => {
			try {
				execFileSync("gh", ["--version"], { stdio: "ignore" });
				return true;
			} catch {
				return false;
			}
		},
	};
}

// ---------------------------------------------------------------------------
// The orchestrator
// ---------------------------------------------------------------------------

export interface PrOptions {
	base?: string;
	draft?: boolean;
}

export type PrOutcome =
	| { kind: "created"; url: string }
	| { kind: "updated"; url: string }
	| { kind: "error"; message: string };

function findExistingPrUrl(env: PrEnv, branch: string): string | null {
	try {
		const out = env.gh(["pr", "view", branch, "--json", "url", "-q", ".url"]);
		return out || null;
	} catch {
		return null;
	}
}

export function runPr(
	repoRoot: string,
	currentBranch: string,
	ticket: Ticket,
	opts: PrOptions,
	env: PrEnv,
): PrOutcome {
	if (!env.hasGh()) {
		return {
			kind: "error",
			message:
				"`gh` CLI not found in PATH. Install from https://cli.github.com/ " +
				"and run `gh auth login` once, or use the local-merge fallback " +
				"documented in /todo-implement step 8.",
		};
	}

	// Push branch first (idempotent; -u sets upstream if not set).
	try {
		env.git(["push", "-u", "origin", currentBranch]);
	} catch (err) {
		return {
			kind: "error",
			message:
				`failed to push '${currentBranch}' to origin: ${(err as Error).message}\n` +
				"  Confirm a git remote is configured and you have push access.",
		};
	}

	const title = makeTitle(ticket.summary);
	const body = makeBody(ticket, repoRoot);

	const existingUrl = findExistingPrUrl(env, currentBranch);
	if (existingUrl) {
		try {
			env.gh(
				["pr", "edit", currentBranch, "--title", title, "--body-file", "-"],
				body,
			);
			return { kind: "updated", url: existingUrl };
		} catch (err) {
			return {
				kind: "error",
				message: `failed to update existing PR: ${(err as Error).message}`,
			};
		}
	}

	const createArgs = ["pr", "create", "--title", title, "--body-file", "-"];
	if (opts.base) createArgs.push("--base", opts.base);
	if (opts.draft) createArgs.push("--draft");

	let url: string;
	try {
		url = env.gh(createArgs, body);
	} catch (err) {
		return {
			kind: "error",
			message: `gh pr create failed: ${(err as Error).message}`,
		};
	}

	// gh prints the URL as the last non-empty line.
	const lines = url
		.split("\n")
		.map((l) => l.trim())
		.filter(Boolean);
	const lastLine = lines[lines.length - 1] ?? "";
	return { kind: "created", url: lastLine };
}
